{{- if .Values.compat03x }}
---
{{- $storageClass := .Values.storageClasses.thin -}}
{{ if $storageClass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-lvm-sc-thin
{{- if not (empty $storageClass.additionalAnnotations) }}
  annotations:
    {{- $storageClass.additionalAnnotations | toYaml | nindent 4 -}}
{{ end }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
provisioner: {{ .Values.lvm.driverName }}
reclaimPolicy: {{ $storageClass.reclaimPolicy }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: "thin"
{{- if not (empty $storageClass.additionalAnnotations) }}
{{ $storageClass.additionalAnnotations | toYaml | nindent 2 }}
{{- end }}
{{ end }}
{{- end }}
