---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: logicalvolumesnapshots.gms.io
spec:
  group: gms.io
  names:
    kind: LogicalVolumeSnapshot
    listKind: LogicalVolumeSnapshotList
    plural: logicalvolumesnapshots
    singular: logicalvolumesnapshot
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: LogicalVolumeSnapshot is the Schema for logicalvolumesnapshots API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value and
              may reject unrecognized values.
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers should infer this from the endpoint the client submits requests to.
              Cannot be updated.
            type: string
          metadata:
            type: object
          spec:
            description: LogicalVolumeSnapshotSpec defines the desired state of LogicalVolumeSnapshot
            properties:
              snapshotName:
                description: The name of the snapshot logical volume
                type: string
              originName:
                description: The name of the origin logical volume
                type: string
            required:
            - snapshotName
            - originName
            type: object
          status:
            description: LogicalVolumeSnapshotStatus defines the observed state of LogicalVolumeSnapshot
            properties:
              message:
                description: A human-readable message indicating details about the snapshot
                type: string
              phase:
                description: LogicalVolumeSnapshotPhase represents the phase of a logical volume snapshot
                type: string
              creationTimestamp:
                description: The creation timestamp of the snapshot
                format: int64
                type: integer
              size:
                description: The size of the snapshot
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
