name: gluesys-csi
version: 1.0.0
description: LVM-based Gluesys Persistent Storage
appVersion: v1.0.0
apiVersion: v1
keywords:
- storage
- block-storage
- volume
home: https://github.com/gluesys
sources:
- https://github.com/gluesys/gluesys-csi
